---
- hosts: dev
  become: True
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
    # - name: Install docker
    #   apt:
    #     name: docker
    #     state: present
    # - name: Start Docker service
    #   systemd:
    #     name: docker  
    #     state: started
    #     enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    
    - name: Stop existing container
      docker_container:
        name: ansible
        state: stopped
      ignore_errors: yes
      
    - name: Start the container
      docker_container:
        name: ansible
        image: "pardhuguttula/ansible:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8088:80
