---
- hosts: dev
  become: True
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
    # - name: Install docker
    #   apt:
    #     name: docker
    #     state: present
    # - name: Start Docker service
    #   systemd:
    #     name: docker  
    #     state: started
    #     enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: Generate unique container name
      set_fact:
        container_name: "ansible_{{ DOCKER_TAG }}"

    # - name: Stop existing container
    #   command: "docker stop ansible{{DOCKER_TAG}}"
    #   ignore_errors: yes

    # - name: Stop existing container
    #   command: "docker stop {{ container_name }}"
    #   ignore_errors: yes
    
    # - name: Wait for existing container to be stopped
    #   command: "docker wait {{ container_name }}"
    #   ignore_errors: yes

    # - name: Start the new container
    #   command: "docker run --name {{ container_name }} -d -p 8088:80 pardhuguttula/ansible:{{ DOCKER_TAG }}"

    - name: Start the new container
      docker_container:
        name: "{{ container_name }}"
        image: "pardhuguttula/ansible:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8088:80